### ISSUE TITLE
Support sending and receiving MMS

### ISSUE THREAD

**Issue by mndrix** [AGWA/sms-over-xmpp#8]
Twilio's API supports this. We could probably use XEP-0363: HTTP File Upload to support it in XMPP.

**Comment by AGWA** [comment]
Any thoughts on how the URL of the uploaded media would be transmitted?  This is out-of-scope of XEP-0363:

> Be agnostic toward the distribution of the actual URL. Users can choose to send the URL in the body of a message stanza, utilize Out-of-Band Data (XEP-0066) [6], Jingle HTTP Transport Method (XEP-0370) [7], or even use it as their avatar in User Avatar (XEP-0084) [8]

I don't think XEP-0363 is needed in sms-over-xmpp itself, since Twilio already uploads the media and provides the URL.  When sms-over-xmpp receives an MMS, it just has to take the URL provided by Twilio and send it over XMPP in such a way (perhaps using XEP-0066) that the user's client understands it.

For sending MMS, the user's client could use XEP-0363 to upload the media somewhere, send the URL in such a way that sms-over-xmpp understands it, and then sms-over-xmpp includes the URL in the request to Twilio.

**Comment by ioscanner** [comment]
Any progress on this?  I have outgoing with a link working.  But the phone on the other end just gets a link, but but they can open it.

Have you figured out a solution for inbound?
